/** Delivery districts served in Metropolitan Lima (and Callao). */
export const LIMA_DISTRICTS = [
  "Ate",
  "Barranco",
  "Breña",
  "Carabayllo",
  "Chorrillos",
  "Comas",
  "El Agustino",
  "Independencia",
  "Jesús María",
  "La Molina",
  "La Victoria",
  "Lima (Cercado)",
  "Lince",
  "Los Olivos",
  "Magdalena del Mar",
  "Miraflores",
  "Pueblo Libre",
  "Puente Piedra",
  "Rímac",
  "San Borja",
  "San Isidro",
  "San Juan de Lurigancho",
  "San Juan de Miraflores",
  "San Luis",
  "San Martín de Porres",
  "San Miguel",
  "Santa Anita",
  "Santiago de Surco",
  "Surquillo",
  "Villa El Salvador",
  "Villa María del Triunfo",
  "Callao",
] as const;
